SET QUOTED_IDENTIFIER OFF;
GO
USE [TimeSheetDB];
GO

INSERT INTO Companies (Code,Name) VALUES 
('Z4M4Q0','Nulla aliquet. Proin velit.'),
('B4J4L6','sem. Pellentesque'),
('Y9P9S3','dui augue'),
('V9A5K4','aliquet diam. Sed diam'),
('Y0U5B3','Donec egestas. Aliquam nec enim.'),
('T3N2Y6','et, commodo'),
('Q6U3Y9','ipsum. Suspendisse sagittis. Nullam vitae'),
('W9J2M9','lectus, a sollicitudin orci'),
('Y3Z9T9','amet orci.'),
('G5R2H7','sit amet'),
('I9G2V2','commodo auctor'),
('F3Y6H5','fermentum arcu.'),
('Y0F6Z2','consequat nec,'),
('W8L1O5','volutpat nunc'),
('M3D2N1','mauris erat eget ipsum. Suspendisse'),
('O9L8M5','non, bibendum'),
('P2C5O2','diam vel arcu. Curabitur ut'),
('C2P6W6','auctor non, feugiat nec,'),
('Z6P5V5','scelerisque neque. Nullam'),
('M7G9G3','eu tempor erat'),
('P4L1T2','elementum, lorem ut aliquam'),
('O1M4W9','Cras vulputate velit eu'),
('Q3I4X5','augue ut lacus. Nulla tincidunt,'),
('H0J5K7','Lorem ipsum dolor'),
('G7D0C7','nascetur ridiculus mus. Aenean eget'),
('Y3B7H7','vulputate, nisi sem semper'),
('D9J0M1','dolor. Nulla semper'),
('G8H6O6','a feugiat tellus lorem'),
('L7V5N6','Curabitur ut'),
('Z2F2A8','Mauris quis'),
('S5E1S6','odio, auctor vitae, aliquet nec,'),
('L2Q9W2','sit amet ornare lectus justo'),
('B6U5J9','ligula consectetuer rhoncus. Nullam velit'),
('E2Q2A8','ac nulla. In'),
('I5X0E8','lobortis tellus'),
('C6P9X4','Fusce diam nunc,'),
('C0N4A4','suscipit nonummy. Fusce fermentum fermentum'),
('S3L7F8','placerat. Cras dictum'),
('J3P5F6','ligula. Aenean'),
('G7H1E5','faucibus. Morbi'),
('Q6S6D4','aliquam iaculis, lacus pede sagittis'),
('X3O0D9','dui lectus rutrum urna,'),
('I2B5V1','non nisi. Aenean eget metus.'),
('Y1G1S3','vitae, sodales at,'),
('A1A1P8','ornare sagittis felis. Donec tempor,'),
('F5P3N2','fringilla cursus purus. Nullam scelerisque'),
('L8K2B2','aliquam adipiscing lacus.'),
('K5D1Z5','Ut nec urna'),
('Q4E2J1','quis lectus. Nullam suscipit,'),
('S2Y2M7','gravida. Aliquam'),
('R4E7T5','id ante dictum cursus.'),
('C8I0J7','enim nisl'),
('H2F6L9','id, mollis'),
('F1K7Z4','libero. Donec consectetuer mauris'),
('Z7J7H0','augue ut lacus. Nulla tincidunt,'),
('Y2M3A5','libero at auctor'),
('V5Y2L1','nec ante blandit'),
('J7J3H9','conubia nostra, per inceptos hymenaeos.'),
('U3A0L9','neque. Nullam nisl.'),
('E9S1O0','Quisque varius. Nam'),
('O4Q0Q0','purus, accumsan interdum libero'),
('V0J1B3','In lorem. Donec'),
('R3Y1I4','enim, gravida sit amet,'),
('J2S9G1','metus. In lorem.'),
('P9W2A5','egestas blandit.'),
('P5Z6X3','lectus. Nullam suscipit,'),
('T4S0V2','turpis. Aliquam adipiscing lobortis'),
('L3D7N4','ullamcorper magna. Sed eu'),
('K3J4Y5','egestas nunc sed'),
('E2F0Q6','velit. Sed malesuada augue'),
('C3M9P1','Nunc sed'),
('K2T9R2','erat. Sed'),
('R3N6Y8','Sed eu'),
('C3E7B8','est mauris,'),
('G6B8T1','Mauris quis turpis vitae purus'),
('J6B0Y1','aliquet, metus'),
('M7G4N4','tempus non, lacinia at,'),
('U7J8Q5','nunc sit amet metus. Aliquam'),
('D0S8E6','malesuada. Integer'),
('H1Q2F7','Morbi quis urna. Nunc quis'),
('N0E0M7','arcu iaculis enim, sit'),
('N0D1O1','Nunc ullamcorper, velit in aliquet'),
('E7O3I6','ante bibendum ullamcorper. Duis cursus,'),
('S5V9I6','ipsum porta elit, a'),
('S8W2O5','arcu et pede. Nunc'),
('P6E1U1','pede. Suspendisse dui. Fusce diam'),
('X4H2A1','egestas lacinia. Sed congue, elit'),
('S6R0I3','Cras convallis convallis dolor. Quisque'),
('D7G6H7','libero. Morbi accumsan laoreet'),
('K8B1B9','lacus. Cras'),
('J4E3Q0','ac risus.'),
('R8K9D2','amet diam'),
('B2X3Z6','Nullam feugiat'),
('M2O5F6','sed turpis nec'),
('D6Y7R0','lacinia vitae,'),
('W4I9U3','eget varius'),
('P1E5T3','faucibus orci luctus et ultrices'),
('R5U8F2','ligula consectetuer rhoncus.'),
('X3C5L1','eget, volutpat ornare, facilisis eget,'),
('R2H4P5','in felis. Nulla');

